ヘッダーのレスポンシブの設定
ait-creators/ait-creators.github.io pull request #4
Opened 2024-07-05 03:50 UTC by Niimijpn

# ヘッダーのレスポンシブの設定

## 概要
ヘッダーのレスポンシブの設定

## イメージ
![mob](https://github.com/ait-creators/ait-creators.github.io/assets/115053448/85d61b58-6d8b-4d45-af5a-8540d2801985)

![pc](https://github.com/ait-creators/ait-creators.github.io/assets/115053448/060bd09b-0e1d-4867-9e80-505217f9e062)

## 確認事項
- [ ] テストの実行と確認

2024-07-05 10:40 UTC, shouta0715 requested changes
@Niimijpn 
１点修正お願いします！！

2024-07-05 10:40 UTC, shouta0715 commented on src/app/(app)/_components/header/index.tsx
>          </div>
h1タグは1ページに1つのほうがSEO的に良いので以下のように1つにしてください！
[MDN 1 つのページに複数の h1 要素を使用しない](https://developer.mozilla.org/ja/docs/Web/HTML/Element/Heading_Elements#1_%E3%81%A4%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AB%E8%A4%87%E6%95%B0%E3%81%AE_h1_%E8%A6%81%E7%B4%A0%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84)


```suggestion
        <h1 className="offside relative z-10 flex text-[4rem] md:text-[8rem]">
          <span className="neon_blue">BeCreate</span>
          <span className="neon_orange rotate-12">!</span>
        </h1>
```

2024-07-05 15:40 UTC, Niimijpn commented on src/app/(app)/_components/header/index.tsx
>          </div>
勉強になります！！

2024-07-06 07:45 UTC, shouta0715 approved these changes
LGTML!

2024-07-06 07:45 UTC, merged