イメージスライダーの作成
ait-creators/ait-creators.github.io pull request #5
Opened 2024-07-06 08:20 UTC by Niimijpn

# イメージスライダーの作成

## 概要
メインビジュアルであるイメージスライダーを作りました．
アニメーションは[framer-motion](https://www.framer.com/motion/)を使っています．
画面サイズの計測には[react-use-measure](https://www.npmjs.com/package/react-use-measure)を使用しています．

## イメージ
![スクリーンショット 2024-07-06 17 12 23](https://github.com/ait-creators/ait-creators.github.io/assets/115053448/798f85ce-a164-4388-af99-acc77d8134b5)

![スクリーンショット 2024-07-06 17 10 40](https://github.com/ait-creators/ait-creators.github.io/assets/115053448/3179fbd3-8842-4fea-8e08-4f963a9d4af3)

## 確認事項
- [ ] テストの実行と確認

## その他
かなり急ぎで作っているのでところどころ雑です（特にモバイル用のレイアウト）

2024-07-06 08:21 UTC, Niimijpn commented on src/app/(app)/page.tsx
> +        <Carousel flag={false} />
画像の流れる方向は`flag`で管理しています

2024-07-06 08:23 UTC, Niimijpn commented on src/lib/data/index.ts
画像パスは他のファイルに記述しましたが，ほかに良い方法があればアドバイスが欲しいです．
また，ファイルの配置場所についてもアドバイスが欲しいです．

2024-07-06 08:25 UTC, Niimijpn commented on src/app/(app)/_components/carousel/index.tsx
[Infinite scrolling carousel with hover effects using Framer Motion
](https://www.youtube.com/watch?v=Ot4nZ6UjJLE0)を参考にしました

2024-07-06 10:33 UTC, shouta0715 requested changes
いくつか確認お願いします！

2024-07-06 10:33 UTC, shouta0715 commented on src/app/(app)/_components/card/index.tsx
> +      onHoverStart={() => setShowOverlay(true)}
できればoverlayはstate使わずにcssだけで行いたいです。
Tailwind CSSには[Hover](https://tailwindcss.com/docs/hover-focus-and-other-states)時にstyleを付与できます。

2024-07-06 10:33 UTC, shouta0715 commented on src/app/(app)/_components/carousel/index.tsx
> +    let controls;
controlsはconstにできます。
そうすれば、 ` // eslint-disable-next-line prefer-const`を消せます。

2024-07-06 10:33 UTC, shouta0715 commented on src/app/(app)/_components/carousel/index.tsx
> +    let finalposition;
firstposition -> firstPosition
finalposition -> firnalPositionの方が良いです！
[code spell check](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code)という拡張機能をいれると、spellの修正が必要なところがわかります。

2024-07-06 10:33 UTC, shouta0715 commented on src/app/(app)/_components/carousel/index.tsx
> +export default function Page({ flag }: { flag: boolean }) {
```suggestion
export default function Page({ flag = true }: { flag?: boolean }) {
```

のようにすると、trueの場合はpropsを省略できます。（知っていて意図的に渡していれば大丈夫です！）

```tsx
<Carousel  />
```
👆のように渡さなくても`true`になる

2024-07-06 10:33 UTC, shouta0715 commented on src/app/(app)/_components/card/index.css
> +}
cssファイルで記せずに、Tailwind CSSを使ってください。
https://tailwindcss.com/docs/skew

2024-07-06 10:33 UTC, shouta0715 commented on src/lib/data/index.ts
データベース使うかとか決まっていない（？）のでとりあえずは大丈夫です！

2024-07-06 10:36 UTC, shouta0715 commented
@Niimijpn 
おそらくCardをクリックしたら個別ページに遷移すると思うので（？）CardをHoverしたらアニメーションが止まるようにしたいです！

2024-07-09 03:15 UTC, Niimijpn commented on src/app/(app)/layout.tsx
画面からはみ出たCardのせいでスクロールできるようになってたのでスクロールしないようにした

2024-07-09 03:35 UTC, Niimijpn commented
https://github.com/ait-creators/ait-creators.github.io/assets/115053448/bca01b18-3a27-4bf1-9bc1-d26658609142

2024-07-09 06:19 UTC, shouta0715 approved these changes
LGTM!!!!
完璧です！
ありがとうございます！！

2024-07-09 13:44 UTC, merged